config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  namespace :admin do
    resources :episodes, only: %w[index edit update new create]
    resource :setting, only: %w[edit update]
  end

  resources :episodes, only: %i[show index], param: :slug
  resource :status, only: %i[show], controller: :status

  root to: "welcome#index"

  get "about", to: "welcome#about", as: :about
  get "imprint", to: "welcome#imprint", as: :imprint
  get "privacy", to: "welcome#privacy", as: :privacy

  get "/sitemap.xml.gz", to: redirect("https://wartenberger-podcast.s3.amazonaws.com/sitemap.xml.gz")
  # episode shortcut /006 or /2
  get ":id", to: "welcome#epsiode", constraints: {id: /\d+/}
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @episodes_records = Episode.published.limit(3)
    @episodes = EpisodePresenter.wrap @episodes_records

    @last_episode = @episodes.first
    fresh_when @episodes_records, public: true
  end

  def imprint
  end

  def privacy
  end

  def epsiode
    epsiode_id = params[:id].to_i.positive? ? params[:id].to_i : nil
    episode_record = Episode.find_by(number: epsiode_id) if epsiode_id

    if episode_record
      redirect_to episode_path slug: episode_record.slug
    else
      redirect_to "/404"
    end
  end

  def about
    #episode_number = current_setting.about_episode_number.presence
    episode = nil # Episode.find_by(number: episode_number)
    @about_episode = episode ? EpisodePresenter.new(episode) : nil
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.haml
- content_for(:html_title) { "Über den Podcast" }
= render "shared/episode_show", episode: @about_episode

.site-section.bg-light
  .container-fluid
    .row.mb-5
      .col-md-12
        %h3.text-center Über Wartenberg TV

        .description.text-center.pt-2
          TODO
- if false
  .site-section
    .container
      .row.mb-5
        .col-md-12.text-center
          %h2.font-weight-bold.text-black Die Gastgeber
      .row

        .col-md-6.col-lg-64.mb-5.mb-lg-5
          .team-member.text-center
            = image_pack_tag("media/images/michael.jpg", class: "img-fluid", alt: "Michael")
            .text
              %h2.mb-2.font-weight-light.h4 Michael Deimel
              %span.d-block.mb-2.text-white-opacity-05 &nbsp;
              %p.mb-4 &nbsp;
              %p
                %a.text-white.p-2{:href => "mailto:michael@wartenberger.de"}
                  %span
                    %i.far.fa-envelope.fa-3x
                %a.text-white.p-2{:href => "https://twitter.com/stereosonnig"}
                  %span
                    %i.fab.fa-twitter.fa-3x
                %a.text-white.p-2{:href => "https://www.facebook.com/michael.deimel.52"}
                  %span
                    %i.fab.fa-facebook.fa-3x
                %a.text-white.p-2{:href => "https://www.xing.com/profile/Michael_Deimel"}
                  %span
                    %i.fab.fa-xing.fa-3x
                %a.text-white.p-2{:href => "https://www.linkedin.com/in/michael-deimel-8a404b17b"}
                  %span
                    %i.fab.fa-linkedin.fa-3x

        .col-md-6.col-lg-6.mb-5.mb-lg-5
          .team-member.text-center
            = image_pack_tag("media/images/thomas.jpg", class: "img-fluid", alt: "Thomas")
            .text
              %h2.mb-2.font-weight-light.h4 Thomas Rademacher
              %span.d-block.mb-2.text-white-opacity-05 &nbsp;
              %p.mb-4 &nbsp;
              %p
                %a.text-white.p-2{:href => "mailto:thomas@wartenberger.de"}
                  %span
                    %i.far.fa-envelope.fa-3x
                %a.text-white.p-2{:href => "https://twitter.com/radiceu"}
                  %span
                    %i.fab.fa-twitter.fa-3x

                %a.text-white.p-2{:href => "https://www.facebook.com/thomas.rademacher1"}
                  %span
                    %i.fab.fa-facebook.fa-3x
                %a.text-white.p-2{:href => "https://www.xing.com/profile/Thomas_Rademacher#"}
                  %span
                    %i.fab.fa-xing.fa-3x
                %a.text-white.p-2{:href => "https://www.linkedin.com/in/thomas-rademacher-652b683"}
                  %span
                    %i.fab.fa-linkedin.fa-3x

app/views/welcome/imprint.html.haml
- title = "Impressum"
- content_for(:html_title) { title }
.site-section.bg-light
  .container-fluid
    .row.mb-5
      .col-md-12
        %h1.text-center
          = title
        .description.text-center.pt-2
          TODO

app/views/welcome/index.html.haml
-# **************************
-# background logo
-# **************************
.site-blocks-cover.overlay-welcome{style: "background-image: url(#{asset_pack_path('media/images/hp-bg-logo-950x600.jpg')});"}
  .container-fluid
    .row.align-items-center.justify-content-center.text-center
      .col-md-8
        = render "shared/episode_inline", episode: @last_episode
-# **************************
-#  episodes
-# **************************

.site-section.bg-light
  .container-fluid
    .row.mb-3
      .col-md-12.text-center
        .subscribe-buttons.justify-content-center.text-white
          -if current_setting.itunes_url.present?
            = link_to(current_setting.itunes_url.strip, class: "btn btn-secondary rounded-pill") do
              %i.fab.fa-apple
              Apple Podcast
          -if current_setting.spotify_url.present?
            = link_to(current_setting.spotify_url.strip, class: " btn btn-secondary rounded-pill") do
              %i.fab.fa-spotify
              Spotify
          -if current_setting.google_url.present?
            = link_to(current_setting.google_url.strip, class: " btn btn-secondary  rounded-pill") do
              %i.fab.fa-google
              Google
          -if current_setting.youtube_url.present?
            = link_to(current_setting.youtube_url.strip, class: " btn btn-secondary rounded-pill") do
              %i.fab.fa-youtube
              Youtube
          = link_to(episodes_path, class: " btn btn-secondary rounded-pill") do
            Alle Episoden

    - if @episodes.present?
      #last-episodes
        .row.mb-3
          .col-md-12.text-center
            %h2.font-weight-bold.text-black Letzte Episoden

        - @episodes.each do |episode|
          .row
            .col-md-12
              = render "shared/episode", episode: episode

      .container-fluid
        .row
          .col.text-center
            = link_to(episodes_path, class: " btn btn-secondary rounded-pill") do
              Alle Episoden

app/views/welcome/privacy.html.haml
- title = "Datenschutz­erklärung"
- content_for(:html_title) { title }
.site-section.bg-light
  .container-flex
    .row.mb-5
      .col-md-12
        %h1.text-center
          = title

        .description.text-center.pt-2
          %h2#1-datenschutz-auf-einen-blick 1. Datenschutz auf einen Blick
          %h3#allgemeine-hinweise Allgemeine Hinweise
          %p
            Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie persönlich identifiziert werden können. Ausführliche Informationen zum Thema Datenschutz entnehmen Sie unserer unter diesem Text aufgeführten Datenschutzerklärung.
          %h3#datenerfassung-auf-dieser-website Datenerfassung auf dieser Website

          %h4#wer-ist-verantwortlich-f-r-die-datenerfassung-auf-dieser-website- Wer ist verantwortlich für die Datenerfassung auf dieser Website?
          %p Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten können Sie dem Abschnitt „Hinweis zur Verantwortlichen Stelle“ in dieser Datenschutzerklärung entnehmen.
          %h4#wie-erfassen-wir-ihre-daten- Wie erfassen wir Ihre Daten?
          %p
            Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z. B. um Daten handeln, die Sie in ein Kontaktformular eingeben.
            Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme erfasst. Das sind vor allem technische Daten (z. B. Internetbrowser, Betriebssystem oder Uhrzeit des Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie diese Website betreten.

          %h4#wof-r-nutzen-wir-ihre-daten- Wofür nutzen wir Ihre Daten?
          %p Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten. Andere Daten können zur Analyse Ihres Nutzerverhaltens verwendet werden.

          %h4#welche-rechte-haben-sie-bez-glich-ihrer-daten- Welche Rechte haben Sie bezüglich Ihrer Daten?
          %p
            Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben außerdem ein Recht, die Berichtigung oder Löschung dieser Daten zu verlangen. Wenn Sie eine Einwilligung zur Datenverarbeitung erteilt haben, können Sie diese Einwilligung jederzeit für die Zukunft widerrufen. Außerdem haben Sie das Recht, unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Des Weiteren steht Ihnen ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu.
            Hierzu sowie zu weiteren Fragen zum Thema Datenschutz können Sie sich jederzeit an uns wenden.

          %h2#2-allgemeine-hinweise-und-pflicht-informationen 2. Allgemeine Hinweise und Pflicht­informationen

          %h3#datenschutz Datenschutz

          %p
            Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung.
            Wenn Sie diese Website benutzen, werden verschiedene personenbezogene Daten erhoben. Personenbezogene Daten sind Daten, mit denen Sie persönlich identifiziert werden können. Die vorliegende Datenschutzerklärung erläutert, welche Daten wir erheben und wofür wir sie nutzen. Sie erläutert auch, wie und zu welchem Zweck das geschieht.
            Wir weisen darauf hin, dass die Datenübertragung im Internet (z. B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.

          %h3#hinweis-zur-verantwortlichen-stelle Hinweis zur verantwortlichen Stelle

          %p
            Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:

            TODO

            Verantwortliche Stelle ist die natürliche oder juristische Person, die allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z. B. Namen, E-Mail-Adressen o. Ä.) entscheidet.

          %h3#speicherdauer Speicherdauer
          %p Soweit innerhalb dieser Datenschutzerklärung keine speziellere Speicherdauer genannt wurde, verbleiben Ihre personenbezogenen Daten bei uns, bis der Zweck für die Datenverarbeitung entfällt. Wenn Sie ein berechtigtes Löschersuchen geltend machen oder eine Einwilligung zur Datenverarbeitung widerrufen, werden Ihre Daten gelöscht, sofern wir keinen anderen rechtlich zulässigen  Gründe für die Speicherung Ihrer personenbezogenen Daten haben (z.B. steuer- oder handelsrechtliche Aufbewahrungsfristen); im letztgenannten Fall erfolgt die Löschung nach Fortfall dieser Gründe.
          %h3#widerruf-ihrer-einwilligung-zur-datenverarbeitung Widerruf Ihrer Einwilligung zur Datenverarbeitung
          %p Viele Datenverarbeitungsvorgänge sind nur mit Ihrer ausdrücklichen Einwilligung möglich. Sie können eine bereits erteilte Einwilligung jederzeit widerrufen. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unberührt.

          %h3 Widerspruchsrecht gegen die Datenerhebung in besonderen Fällen sowie gegen Direktwerbung (Art. 21 DSGVO)
          %p
            WENN DIE DATENVERARBEITUNG AUF GRUNDLAGE VON ART. 6 ABS. 1 LIT. E ODER F DSGVO ERFOLGT, HABEN SIE JEDERZEIT DAS RECHT, AUS GRÜNDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIE VERARBEITUNG IHRER PERSONENBEZOGENEN DATEN WIDERSPRUCH EINZULEGEN; DIES GILT AUCH FÜR EIN AUF DIESE BESTIMMUNGEN GESTÜTZTES PROFILING. DIE JEWEILIGE RECHTSGRUNDLAGE, AUF DENEN EINE VERARBEITUNG BERUHT, ENTNEHMEN SIE DIESER DATENSCHUTZERKLÄRUNG. WENN SIE WIDERSPRUCH EINLEGEN, WERDEN WIR IHRE BETROFFENEN PERSONENBEZOGENEN DATEN NICHT MEHR VERARBEITEN, ES SEI DENN, WIR KÖNNEN ZWINGENDE SCHUTZWÜRDIGE GRÜNDE FÜR DIE VERARBEITUNG NACHWEISEN, DIE IHRE INTERESSEN, RECHTE UND FREIHEITEN ÜBERWIEGEN ODER DIE VERARBEITUNG DIENT DER GELTENDMACHUNG, AUSÜBUNG ODER VERTEIDIGUNG VON RECHTSANSPRÜCHEN (WIDERSPRUCH NACH ART. 21 ABS. 1 DSGVO).
            WERDEN IHRE PERSONENBEZOGENEN DATEN VERARBEITET, UM DIREKTWERBUNG ZU BETREIBEN, SO HABEN SIE DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE VERARBEITUNG SIE BETREFFENDER PERSONENBEZOGENER DATEN ZUM ZWECKE DERARTIGER WERBUNG EINZULEGEN; DIES GILT AUCH FÜR DAS PROFILING, SOWEIT ES MIT SOLCHER DIREKTWERBUNG IN VERBINDUNG STEHT. WENN SIE WIDERSPRECHEN, WERDEN IHRE PERSONENBEZOGENEN DATEN ANSCHLIESSEND NICHT MEHR ZUM ZWECKE DER DIREKTWERBUNG VERWENDET (WIDERSPRUCH NACH ART. 21 ABS. 2 DSGVO).

          %h3#beschwerde-recht-bei-der-zust-ndigen-aufsichts-beh-rde Beschwerde­recht bei der zuständigen Aufsichts­behörde
          %p Im Falle von Verstößen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat ihres gewöhnlichen Aufenthalts, ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes zu. Das Beschwerderecht besteht unbeschadet anderweitiger verwaltungsrechtlicher oder gerichtlicher Rechtsbehelfe.
          %h3#recht-auf-daten-bertrag-barkeit Recht auf Daten­übertrag­barkeit
          %p Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erfüllung eines Vertrags automatisiert verarbeiten, an sich oder an einen Dritten in einem gängigen, maschinenlesbaren Format aushändigen zu lassen. Sofern Sie die direkte Übertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.
          %h3#ssl-bzw-tls-verschl-sselung SSL- bzw. TLS-Verschlüsselung
          %p
            Diese Seite nutzt aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, wie zum Beispiel Bestellungen oder Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL- bzw. TLS-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von „http://“ auf „https://“ wechselt und an dem Schloss-Symbol in Ihrer Browserzeile.
            Wenn die SSL- bzw. TLS-Verschlüsselung aktiviert ist, können die Daten, die Sie an uns übermitteln, nicht von Dritten mitgelesen werden.
          %h3#auskunft-l-schung-und-berichtigung Auskunft, Löschung und Berichtigung
          %p Sie haben im Rahmen der geltenden gesetzlichen Bestimmungen jederzeit das Recht auf unentgeltliche Auskunft über Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empfänger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung oder Löschung dieser Daten. Hierzu sowie zu weiteren Fragen zum Thema personenbezogene Daten können Sie sich jederzeit an uns wenden.
          %h3#recht-auf-einschr-nkung-der-verarbeitung Recht auf Einschränkung der Verarbeitung
          %p
            Sie haben das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.
            Hierzu können Sie sich jederzeit an uns wenden. Das Recht auf Einschränkung der Verarbeitung besteht in folgenden Fällen:
          %ul
            %li Wenn Sie die Richtigkeit Ihrer bei uns gespeicherten personenbezogenen Daten bestreiten, benötigen wir in der Regel Zeit, um dies zu überprüfen. Für die Dauer der Prüfung haben Sie das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.
            %li Wenn die Verarbeitung Ihrer personenbezogenen Daten unrechtmäßig geschah/geschieht, können Sie statt der Löschung die Einschränkung der Datenverarbeitung verlangen.
            %li Wenn wir Ihre personenbezogenen Daten nicht mehr benötigen, Sie sie jedoch zur Ausübung, Verteidigung oder Geltendmachung von Rechtsansprüchen benötigen, haben Sie das Recht, statt der Löschung die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.
            %li
              Wenn Sie einen Widerspruch nach Art. 21 Abs. 1 DSGVO eingelegt haben, muss eine Abwägung zwischen Ihren und unseren Interessen vorgenommen werden. Solange noch nicht feststeht, wessen Interessen überwiegen, haben Sie das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.
              Wenn Sie die Verarbeitung Ihrer personenbezogenen Daten eingeschränkt haben, dürfen diese Daten – von ihrer Speicherung abgesehen – nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen oder zum Schutz der Rechte einer anderen natürlichen oder juristischen Person oder aus Gründen eines wichtigen öffentlichen Interesses der Europäischen Union oder eines Mitgliedstaats verarbeitet werden.
              Quelle:
              %a{:href => "https://www.e-recht24.de"} eRecht24