config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  namespace :admin do
    resources :episodes, only: %w[index edit update new create]
    resource :setting, only: %w[edit update]
  end

  resources :episodes, only: %i[show index], param: :slug
  resource :status, only: %i[show], controller: :status

  root to: "welcome#index"

  get "about", to: "welcome#about", as: :about
  get "imprint", to: "welcome#imprint", as: :imprint
  get "privacy", to: "welcome#privacy", as: :privacy

  get "/sitemap.xml.gz", to: redirect("https://wartenberger-podcast.s3.amazonaws.com/sitemap.xml.gz")
  # episode shortcut /006 or /2
  get ":id", to: "welcome#epsiode", constraints: {id: /\d+/}
end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id              :bigint           not null, primary key
#  active          :boolean          default(TRUE)
#  artwork_url     :string
#  chapter_marks   :text
#  description     :text             not null
#  downloads_count :integer          default(0)
#  nodes           :text
#  number          :integer          default(0), not null
#  published_on    :date
#  slug            :string           not null
#  title           :string           not null
#  youtube_key     :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_episodes_on_number        (number) UNIQUE
#  index_episodes_on_published_on  (published_on)
#  index_episodes_on_slug          (slug) UNIQUE
#  index_episodes_on_title         (title) UNIQUE
#
class Episode < ApplicationRecord
  def to_param
    slug
  end

  scope :published, -> { where(active: true).where("published_on <= ?", Time.zone.today).order(number: :desc) }

  validates(:number, uniqueness: true)
  validates(:slug, uniqueness: true)
  validates(:title, uniqueness: true)
end

app/controllers/admin/episodes_controller.rb
module Admin
  class EpisodesController < BaseController
    def index
      @episode_records = Episode.order("number desc")
      @episodes = EpisodePresenter.wrap @episode_records
    end

    def new
      @episode = Episode.new number: Episode.maximum(:number).to_i.next
    end

    def create
      @episode = Episode.new create_params
      @episode.slug = build_slug(@episode)
      if @episode.save
        redirect_to admin_episodes_path, notice: "Episode was successfully created."
      else
        render :new
      end
    end

    def edit
      @episode = Episode.find_by!(slug: params[:id])
    end

    def update
      @episode = Episode.find_by!(slug: params[:id])
      if @episode.update(update_params) && @episode.update(slug: build_slug(@episode))
        redirect_to admin_episodes_path, notice: "Episode was successfully updated."
      else
        render :edit
      end
    end

    protected

    def build_slug(episode)
      return if episode.number.blank? || episode.title.blank?
      "#{episode.number.to_s.rjust(3, "0")} #{episode.title}".parameterize(locale: :de)
    end

    def create_params
      params.require(:episode).permit(*Episode::ATTRIBUTES)
    end

    def update_params
      params.require(:episode).permit(*Episode::ATTRIBUTES)
    end
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @episodes_records = Episode.published.paginate(page: params[:page], per_page: params[:per_page])
    @episodes = EpisodePresenter.wrap @episodes_records

    respond_to do |format|
      format.html
      format.rss do
        @feed = PodcastFeedPresenter.new(@episodes)
        render layout: false, content_type: "application/xml"
      end
    end
  end

  def show
    episode_record = Episode.find_by!(slug: params[:slug])
    @episode = EpisodePresenter.new episode_record
    if stale? episode_record, public: true
      respond_to do |format|
        # ETag caching https://api.rubyonrails.org/classes/ActionController/ConditionalGet.html#method-i-stale-3F
        format.html
        format.mp3 do
          episode_record.increment! :downloads_count unless params[:notracking]
          redirect_to @episode.file_url
        end
      end
    end
  end
end

app/helpers/admin/episodes_helper.rb
module Admin
  module EpisodesHelper
  end
end

app/views/admin/episodes/_form.html.haml
= f.input :title
= show_button "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet", "Markdown Help"
= f.input :description, as: :text, input_html: { cols: 5, rows: 10 }
= f.input :nodes, as: :text, input_html: { cols: 5, rows: 10 }
= f.input :youtube_key,  hint: "YouTube Id: e.g.: https://www.youtube.com/watch?v=ABC => ABC is the key"
= f.input :published_on, as: :date, html5: true
= f.input :active, as: :boolean

app/views/admin/episodes/edit.html.haml
.site-section.bg-light
  .container
    .row
      .col-md-12
        %h1 Editing Episode
        = simple_form_for([:admin, @episode], html: { class: 'form-horizontal' })do |f|
          = f.error_notification
          = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

          .form-inputs
            = render "form", f: f
          .form-actions
            = submit_button

        = back_button admin_episodes_path

app/views/admin/episodes/index.html.haml
.bg-ligh

  %h1 Episodes
  %table.table.table-striped.table-bordered
    %thead.thead-dark
      %tr
        %th Published
        %th Epsiode
        %th Title
        %th Link
        %th Published
        %th
        %th
    %tbody
      - @episodes.each do |episode|
        %tr{id: "episode-#{episode.id}", class: "text-nowrap #{'inactive' unless episode.published?}"}
          %td= show_boolean_value episode.published?
          %td= episode.number
          %td= episode.title
          %td= link_to episode.youtube_link, episode.youtube_link
          %td= episode.published_on
          %td= edit_button edit_admin_episode_path(episode)
          %td= show_button episode_path(episode)
  %br
  = add_button  new_admin_episode_path

app/views/admin/episodes/new.html.haml
.site-section.bg-light
  .container
    .row
      .col-md-12
        %h1 New Episode
        = simple_form_for([:admin, @episode], html: { class: 'form-horizontal' })do |f|
          = f.error_notification
          = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

          .form-inputs
            = f.input :number
            = render "form", f: f
          .form-actions
            = submit_button

        = back_button admin_episodes_path