config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  namespace :admin do
    resources :episodes, only: %w[index edit update new create]
    resource :setting, only: %w[edit update]
  end

  resources :episodes, only: %i[show index], param: :slug
  resource :status, only: %i[show], controller: :status

  root to: "welcome#index"

  get "about", to: "welcome#about", as: :about
  get "imprint", to: "welcome#imprint", as: :imprint
  get "privacy", to: "welcome#privacy", as: :privacy

  get "/sitemap.xml.gz", to: redirect("https://wartenberger-podcast.s3.amazonaws.com/sitemap.xml.gz")
  # episode shortcut /006 or /2
  get ":id", to: "welcome#epsiode", constraints: {id: /\d+/}
end

app/views/layouts/application.html.haml
!!!
%html{lang: current_setting.language}
  %head
    %title= content_for?(:html_title) ? yield(:html_title) : current_setting.title

    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport" }

    %meta{:content => current_setting.description,  :name => "description"}
    %meta{:content => current_setting.seo_keywords, :name => "keywords" }
    %meta{:content => current_setting.author,       :name => "author" }

    - # Open Graph
    - # https://stackoverflow.com/questions/19778620/provide-an-image-for-whatsapp-link-sharing
    %meta{:property => "og:locale", :content => "de_DE"}

    - if content_for?(:meta_tags)
      = yield(:meta_tags)
    - else
      %meta{:property => "og:title",       :content => current_setting.title }
      %meta{:property => "og:url",         :content => current_setting.canonical_url }
      %meta{:property => "og:description", :content => current_setting.description }
      %meta{:property => "og:image",       :content => current_setting.logo_url, itemprop: "image"}

    - # all favicon
    = render "shared/favicon"

    %link{:href => current_setting.canonical_url, :rel => "canonical"}

    = auto_discovery_link_tag :rss, current_setting.rss_url
    = csrf_meta_tags
    = csp_meta_tag

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

  %body{id: "main", :class => "#{controller_name} #{action_name}"}
    %header
      - if flash.present?
        - flash.each do |name, msg|
          - if msg.is_a?(String)
            %div{id: "top-alert", class: "alert alert-dismissible fade show alert-#{name == :notice ? "success" : "warning"}", role: "alert"}
              %a.close{"data-dismiss" => "alert"} ×
              = content_tag :div, msg, :id => "flash_#{name}"

      %nav.navbar.navbar-dark.bg-dark.navbar-expand-lg
        %h1
          %a.text-white{:href => root_path}
            = current_setting.title
        %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon

        #navbarNav.collapse.text-white.navbar-collapse
          %ul.navbar-nav.ml-auto
            %li.nav-item
              %a.text-white.nav-link{:href => episodes_path} Episoden
            %li.nav-item
              %a.text-white.text-nowrap.nav-link{:href => about_path } Über uns
            - if user_signed_in?
              - if current_user&.admin?
                = link_to "Administration", admin_episodes_path, class: "nav-link text-white"
                = link_to "Settings", edit_admin_setting_path, class: "nav-link text-white"
              = link_to "Account", edit_user_registration_path, class: "nav-link text-white"
              = link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link text-white"
    %main
      .container-fluid

        .content
          = yield

    %footer.site-footer
      .container
        .row
          .col-lg-4
            .mb-5
              %h3.footer-heading.mb-4 Wartenberg TV
              %p
                = current_setting.description

          .col-lg-4.mb-5.mb-lg-0
            .row.mb-5
              .col-md-12
                %h3.footer-heading.mb-4 Navigation
              .col-md-6.col-lg-6
                %ul.list-unstyled
                  %li
                    %a{:href => root_path } Home
                  %li
                    %a{:href => episodes_path } Episoden
                  -# %li
                  -#   %a{:href => new_user_session_path } Login
              .col-md-6.col-lg-6
                %ul.list-unstyled
                  %li
                    %a{:href => about_path} Über Uns
                  %li
                    %a{:href => imprint_path} Impressum
                  %li
                    %a{:href => privacy_path} Datenschutz

          .col-lg-4.mb-5.mb-lg-0
            .mb-5
              %h3.footer-heading.mb-4 Folge uns
              %div
                -if current_setting.facebook_url.present?
                  %a.pl-0.pr-3{:href => current_setting.facebook_url.strip}
                    %span
                      %i.fab.fa-facebook


                -if current_setting.twitter_url.present?
                  %a.pl-0.pr-3{:href => current_setting.twitter_url.strip }
                    %span
                      %i.fab.fa-twitter

                -if current_setting.instagram_url.present?
                  %a.pl-0.pr-3{:href => current_setting.instagram_url.strip }
                    %span
                      %i.fab.fa-instagram

                -if current_setting.itunes_url.present?
                  %a.pl-0.pr-3{:href => current_setting.itunes_url.strip }
                    %span
                      %i.fab.fa-apple

                -if current_setting.spotify_url.present?
                  %a.pl-0.pr-3{:href => current_setting.spotify_url.strip}
                    %span
                      %i.fab.fa-spotify

                -if current_setting.google_url.present?
                  %a.pl-0.pr-3{:href => current_setting.google_url.strip}
                    %span
                      %i.fab.fa-google
                -if current_setting.youtube_url.present?
                  %a.pl-0.pr-3{:href => current_setting.youtube_url.strip}
                    %span
                      %i.fab.fa-youtube
                -if current_setting.rss_url.present?
                  %a.pl-0.pr-3{:href => current_setting.rss_url.strip}
                    %span
                      %i.fas.fa-rss

        .row.text-center
          .col-md-12
            %p
              Copyright ©
              = Date.current.year
              %a{:href => current_setting.email, :target => "_blank"}
                Wartenberger